sudo: false
language: python
env:
  - TOXENV=py27-unittests
  - TOXENV=py34-unittests
  - TOXENV=py35-unittests
  - TOXENV=lint
install:
  - pip install tox
  - pip install codecov
script:
  - tox
after_success:
  - codecov
