site_name: Rummage Documentation
repo_url: https://github.com/facelessuser/Rummage/
site_description: A search and replace tool written in Python.
pages:
  - About Rummage: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Contributing &amp; Support: contributing.md
  - Changelog: changelog.md
  - License: license.md
theme: readthedocs
theme_dir: doc_theme
markdown_extensions:
  - markdown.extensions.toc
  - markdown.extensions.admonition
  - markdown.extensions.smarty
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.extra
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.smartsymbols
  - pymdownx.githubemoji
  - pymdownx.tasklist
  - pymdownx.progressbar
  - pymdownx.headeranchor
